[C++23] Fix unique_ptr error for FileDescriptor
C++23 changed unique_ptr to a constexpr so you need the type to be
completely defined before you pass it to unique_ptr. We fixed this
incomplete type for FileDescriptor by including the header
payload_consumer/file_descriptor.h containing the full definition of
FileDescriptor.

By adding the header, we need to make sure all libraries' C/C++ files
that include cow_reader.h transitively should be able to find the
file_descriptor.h header. We fix it by adding libupdate_engine_headers
(contains file_descriptor.h) to each library's rule.

Errors:
prebuilts/clang/host/linux-x86/clang-r584948/include/c++/v1/__memory/unique_ptr.h:75:19:
error: invalid application of 'sizeof' to an incomplete type
'chromeos_update_engine::FileDescriptor'
   75 |     static_assert(sizeof(_Tp) >= 0, "cannot delete an incomplete
type");
...
system/fs/fs_mgr/libsnapshot/include/libsnapshot/cow_reader.h:28:7:
note: forward declaration of 'chromeos_update_engine::FileDescriptor'
   28 | class FileDescriptor;

Flag: EXEMPT PURE_REFACTOR
Bug: 429048222
Test: m update_engine_unittests
Change-Id: Ifa2cd2e00d35410b2712f88bd06464e9c12fc5fd